{% set name = "shillelagh" %}
{% set version = "1.2.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/shillelagh-{{ version }}.tar.gz
  sha256: 6d4140a029bfafc2e0a217de3e5e34ff4d220f0d969d37cb849dac8f805e28b5

build:
  noarch: python
  entry_points:
    - shillelagh = shillelagh.console:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=46.1.0,<50
    - setuptools-scm >=5
    - wheel
    - pyscaffold >=3.2a0
    - pip
  run:
    - python >=3.8
    - importlib-metadata
    - apsw >=3.9.2
    - python-dateutil >=2.8.1
    - requests >=2.31.0
    - requests-cache >=0.7.1
    - sqlalchemy >=1.3
    - greenlet >=2.0.2
    - typing-extensions >=3.7.4.3
    - packaging

test:
  imports:
    - shillelagh
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/betodealmeida/shillelagh/
  summary: Making it easy to query APIs via SQL
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
